config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  resources :posts, except: [:destroy] do
    resources :comments do
      member do
        post :vote
      end
    end
      

    member do 
      post :vote
    end
  end 

  resources :password_reset, except: [:destroy]

  resources :categories

  get 'register', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  get 'confirm_user', to: 'password_reset#confirm_password'
  post 'confirm_user', to: 'password_reset#auth_confirm_password'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user, foreign_key: :user_id
	belongs_to :post, foreign_key: :post_id

  validates :body, presence: true

  include Voteable
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :select_comment, only: [:vote]
  before_action :require_user, except: [:vote]
  before_action :require_user_to_vote, only: [:vote]
  before_action :require_creator, only: [:edit,:update]

  def new
    @comment = Comment.new
  end


  def create
    @post = Post.find_by(slug: params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user

    if @comment.save
      flash["notice"] = "comment was successfully created"
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end
  end

  def vote
    @vote = Vote.create(voteable: @comment, vote: params[:vote], user: current_user)

    respond_to do |format|
      format.html {redirect_to :back, notice: "Your vote was recorded"}
      format.js
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end

  def select_comment
    @comment = Comment.find(params[:id])
  end

    # check if current user created post or comment
  def require_creator
    deny_access unless logged_in? && current_user.is_creator?(@comment)
  end
end

app/views/comments/_comments.html.erb
<div class = 'row'>
  <div class = 'span0 well text-center'>
      <%= link_to vote_post_comment_path(comment.post, comment, vote: true), method: 'post', remote: true do %>
        <i class = 'icon-thumbs-up'></i>
      <% end %>

  <br/>
    <span id = "comment_<%=comment.id%>"> <%= pluralize(comment.vote_popular, 'like') %> </span>
  <br/> 

     <%= link_to vote_post_comment_path(comment.post, comment, vote: false), method: 'post', remote: true do %>
      <i class = 'icon-thumbs-down'></i>
    <% end %>
  </div>

  <div class = 'span8 well'>
  <p> <%= comment.body %> </p>
  <span class = 'quiet'> by </span> <%= link_to "#{comment.user.username}", user_path(comment.user) %>
  <small> at <%= display_datetime(comment.created_at) %> </small>
  <% if show_post %>
    on <%= link_to "#{comment.post.title}", post_path(comment.post) %>
  <% end %>
  </div>
</div>

app/views/comments/vote.js.erb
<% if @vote.valid? %>
  $("#comment_<%=@comment.id%>").html("<%=pluralize(@comment.vote_popular,'like') %>");
<% else %>
  alert('You can only vote once');
<% end %>