config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  resources :posts, except: [:destroy] do
    resources :comments do
      member do
        post :vote
      end
    end
      

    member do 
      post :vote
    end
  end 

  resources :password_reset, except: [:destroy]

  resources :categories

  get 'register', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  get 'confirm_user', to: 'password_reset#confirm_password'
  post 'confirm_user', to: 'password_reset#auth_confirm_password'

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user, foreign_key: :user_id
	has_many :comments, foreign_key: :post_id
  has_many :post_category_connects, foreign_key: :post_id
  has_many :categories, through: :post_category_connects

  validates :title, presence: true

  before_save :generate_slug
   
  include Voteable
  include Slug

  sluggable_column :title
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :select_post, only: [:show,:edit,:update,:vote]
  before_action :require_user, except: [:index,:show, :vote]
  before_action :require_user_to_vote, only: [:vote]
  before_action :require_creator, only: [:edit,:update]
    
  def index
    @posts = Post.all
  end

  def show
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    if @post.save
      flash["notice"] = "Your post was successfully created"
      redirect_to posts_path
    else
      render :new
    end

  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash["notice"] = "Your post was successfully updated"
      redirect_to posts_path
    else
      render :edit
    end
  end

  def vote
    @vote = Vote.create(voteable: @post, vote: params[:vote], user: current_user)

    respond_to do |format|
      format.html {redirect_to :back, notice: "Your vote was recorded"}
      format.js
    end
  
  end


  private 
  def post_params
    params.require(:post).permit!
  end

  def select_post
    @post = Post.find_by(slug: params[:id])
  end

   # check if current user created post or comment
  def require_creator
    deny_access unless logged_in? && current_user.is_creator?(@post)
  end
end

app/views/posts/_form.html.erb
<%= render 'shared/posterror', object: @post %>

<%= form_for @post do |f| %>
  <%= f.label :title, class: 'whiten'%>
  <%= f.text_field :title %> <br/>
  <%= f.label :url, class: 'whiten' %>
  <%= f.text_field :url %> <br/>
  <%= f.label :description, class: 'whiten' %>
  <%= f.text_area :description, size: "200x12", class: "span4" %><br/>

  <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |checkb| %>
     <% checkb.label(class: "checkbox inline whiten") {checkb.check_box(class: "checkbox") + checkb.text} %> 
     <% end %>

  <br/>
  <br/>

  <%= f.submit action, class: "btn btn-primary btn-large" %>
<% end %>

app/views/posts/_post.html.erb
<div class = 'row'>
  <div class = 'span0 well text-center'>
     <%= link_to vote_post_path(post, vote: true), method: 'post', remote: true do %>
      <i class = 'icon-thumbs-up'></i>
      <% end %>

  <br/>
  <br/>
    <span id = "post_<%=post.slug%>"> <%= pluralize(post.vote_popular, 'like') %> </span>
  <br/> 
  <br/>

    <%= link_to vote_post_path(post, vote: false), method: 'post', remote: true do %>
    <i class = 'icon-thumbs-down'></i>
    <% end %>
  </div>

  <div class = 'span8 well'>
    <%= render post.categories %>
    
    <h4><%= link_to post.title, post_path(post) %> </h4>
    <hr/>
    <p><%= post.description %> </p>
    <span class = 'quiet'> posted by </span> <%= link_to "#{post.user.username}", user_path(post.user) %>
    <small> at <%= display_datetime(post.created_at) %> </small>
    <p>
      <%= link_to pluralize(post.comments.size, "comment"), post_path(post) %>
    </p>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render 'shared/header', title: "Edit post" %>

<%= render 'form', action: "Update" %>

app/views/posts/index.html.haml
%h2.header.whiten 
  Welcome To DanYeboah Financials 
%h4.header.whiten 
  A Forum for Discussing Private Equity and FinTech
%hr

= render 'shared/header', title: 'Financial Posts'

= if logged_in?
  %p 
    = link_to new_post_path do
      %button.btn.btn-success 
        %i.icon-plus 
          New Post



= @posts.each do |post|
  = render 'post', post: post

app/views/posts/new.html.erb
<%= render 'shared/header', title: "Create a new post" %>

<%= render 'form', action: "Create" %>

app/views/posts/show.html.erb
<div class = 'row'>
  <div class = 'well span8'>
    <%= render @post.categories %>
    <h5 class = 'lead'> <%= @post.title %> </h5> 
    <hr/>
  <p><%= @post.description %> </p>
    <% if logged_in? && current_user.is_creator?(@post) %>
    <small> <%= link_to 'Edit Post', edit_post_path(@post) %> </small>
    <% end %>
 </div>
</div>

<hr/>

<%= render 'shared/posterror', object:@comment %>

<% if logged_in? %>
  <%= form_for [@post,@comment] do |f| %>
    <%= f.label "Post a comment", class: 'whiten' %>
    <%= f.text_area :body %> <br/>
    <%= f.submit "Leave comment", class: "btn btn-primary" %>
  <% end %>
 
  <% else %>
  <p class = 'whiten'> Please log in to leave a comment </p> 
<% end %>
<br/>

<h4 class = 'lead whiten'> Comments </h4> <hr/>
<% @post.comments.each do |comment| %>
  <%= render 'comments/comments', comment: comment, show_post: false %>
<% end %>

app/views/posts/vote.js.erb
<% if @vote.valid? %>
  $("#post_<%=@post.slug%>").html("<%= pluralize(@post.vote_popular, 'like') %>");
<% else %>
  alert('You can only vote once');
<% end %>