config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  resources :posts, except: [:destroy] do
    resources :comments do
      member do
        post :vote
      end
    end
      

    member do 
      post :vote
    end
  end 

  resources :password_reset, except: [:destroy]

  resources :categories

  get 'register', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  get 'confirm_user', to: 'password_reset#confirm_password'
  post 'confirm_user', to: 'password_reset#auth_confirm_password'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :post_category_connects, foreign_key: :category_id
  has_many :posts, through: :post_category_connects

  validates :name, presence: true

  before_save :generate_slug

  include Slug
  sluggable_column :name

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, only: [:new,:create]

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      flash["notice"] = "#{@category.name} was successfully created"
      redirect_to '/'
    else
      render :new
    end

  end

  def show
    @category = Category.find_by(slug: params[:id])
  end


  private
  def category_params
    params.require(:category).permit(:name)
  end




end

app/views/categories/_category.html.erb
<span class = 'badge'><%= link_to category.name, category_path(category) %></span>

app/views/categories/new.html.erb
<%= render 'shared/header', title: "Create a new category" %>

<%= render 'shared/posterror', object: @category %>

<%= form_for @category do |f| %>
  <%= f.label :name, class: "whiten" %>
  <%= f.text_field :name %> </br>
  <%= f.submit "Create Category", class: "btn btn-primary" %>
<% end %>

app/views/categories/show.html.erb
<% all_posts = link_to 'All Posts', posts_path %>

<%= render 'shared/header', title: "#{all_posts} &raquo; #{@category.name}".html_safe %>

<% @category.posts.each do |post| %>
  <%= render 'posts/post', post: post %>
<% end %>