config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  resources :posts, except: [:destroy] do
    resources :comments do
      member do
        post :vote
      end
    end
      

    member do 
      post :vote
    end
  end 

  resources :password_reset, except: [:destroy]

  resources :categories

  get 'register', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  get 'confirm_user', to: 'password_reset#confirm_password'
  post 'confirm_user', to: 'password_reset#auth_confirm_password'

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == "notice" ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="mynav">
  <li>
    <%= link_to "Home", root_path, class: 'brand' %>
  </li>

  <li>
    <div class='btn-group nav_item'>
      <%= link_to '#', class: 'btn btn-small dropdown-toggle mynav', 'data-toggle' =>'dropdown' do %>
      Categories <span class ='caret'></span>
      <% end %>

      <ul class='dropdown-menu'>
        <% Category.all.each do |category| %>
        <li>
          <%= link_to category.name, category_path(category) %>
        </li>
        <% end %>
        
        <% if logged_in? && current_user.is_admin? %>
        
          <li class='divider'></li>
          <li> <%= link_to new_category_path do %>
            <i class="icon-plus"></i>
            New Category
            <% end %>
          </li>
        <% end %>
        
      </ul>
    </div>
  </li>

  <% if logged_in? %>
    <div class='btn-group nav_item'>
      <%= link_to '#', class: 'btn btn-small btn-success dropdown-toggle mynav', 'data-toggle' =>'dropdown' do %>
      Hello <%= current_user.username %><span class ='caret'></span>
      <% end %>

      <ul class='dropdown-menu'>
        <li> <%= link_to user_path(current_user) do %>
             <i class = "icon-user"></i> Show Profile
             <% end %>
        </li>
        <li> <%= link_to edit_user_path(current_user) do %>
             <i class = "icon-pencil"></i> Edit Profile
             <% end %>
        </li>
        <li> <%= link_to logout_path do %>
            <i class = "icon-remove-circle"></i> Log out
            <% end %>
        </li>


      </ul>
    </div>

  <% else %>

    <li class = "upbutton">
    <%= link_to "Sign Up!", register_path, class: 'btn btn-primary' %>
  </li>

   <li class = "upbutton">
      <%= link_to "Log in", login_path, class: 'btn btn-success' %>
    </li>
  
  

  <% end %>

</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Danyeboah_PostIt</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>